// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDel8-Bv1a7Z8l6zKriDfDGMptPgQSaN1A',
    appId: '1:560241990086:web:eebac1cb67c1fe0806fac7',
    messagingSenderId: '560241990086',
    projectId: 'poketjob-4e066',
    authDomain: 'poketjob-4e066.firebaseapp.com',
    storageBucket: 'poketjob-4e066.appspot.com',
    measurementId: 'G-WLFMZVHQL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCECHBFnPnClHM9A42VLNDOKRwRmgVH87E',
    appId: '1:560241990086:android:349d17c95a2f129306fac7',
    messagingSenderId: '560241990086',
    projectId: 'poketjob-4e066',
    storageBucket: 'poketjob-4e066.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2M7sfHBpjlysm1ohPgzw_5XfxMewAzqg',
    appId: '1:560241990086:ios:5fde9199783700fc06fac7',
    messagingSenderId: '560241990086',
    projectId: 'poketjob-4e066',
    storageBucket: 'poketjob-4e066.appspot.com',
    iosBundleId: 'com.example.pocketjob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2M7sfHBpjlysm1ohPgzw_5XfxMewAzqg',
    appId: '1:560241990086:ios:5fde9199783700fc06fac7',
    messagingSenderId: '560241990086',
    projectId: 'poketjob-4e066',
    storageBucket: 'poketjob-4e066.appspot.com',
    iosBundleId: 'com.example.pocketjob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDel8-Bv1a7Z8l6zKriDfDGMptPgQSaN1A',
    appId: '1:560241990086:web:77337295f7b487a006fac7',
    messagingSenderId: '560241990086',
    projectId: 'poketjob-4e066',
    authDomain: 'poketjob-4e066.firebaseapp.com',
    storageBucket: 'poketjob-4e066.appspot.com',
    measurementId: 'G-3S7YQ7CMGM',
  );
}
